version: '3.8'

services:
  postgres:
    image: postgres:13    # PostgreSQL 이미지 (버전은 필요에 따라 조정)
    container_name: my_postgres
    environment:
      POSTGRES_DB: postgres        # 기본 데이터베이스 이름
      POSTGRES_USER: postgres      # PostgreSQL 사용자 이름
      POSTGRES_PASSWORD: postgres123 # PostgreSQL 비밀번호
    ports:
      - "5432:5432"                # 호스트와 컨테이너의 포트를 매핑
    volumes:
      - pgdata:/var/lib/postgresql/data # 데이터가 유지되도록 볼륨 설정



volumes:
  pgdata:
